// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.API.Data;

#nullable disable

namespace Shared.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260403135631_AddCompanyIdnetity")]
    partial class AddCompanyIdnetity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Common.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "contact@techsolutions.com",
                            Name = "Tech Solutions",
                            PhoneNumber = "+1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "info@globallogistics.com",
                            Name = "Global Logistics",
                            PhoneNumber = "+1987654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "hello@creativeagency.net",
                            Name = "Creative Agency",
                            PhoneNumber = "+1122334455"
                        },
                        new
                        {
                            Id = 4,
                            Email = "support@summitretail.com",
                            Name = "Summit Retail",
                            PhoneNumber = "+1555666777"
                        },
                        new
                        {
                            Id = 5,
                            Email = "admin@oceanic.org",
                            Name = "Oceanic Corp",
                            PhoneNumber = "+1444333222"
                        },
                        new
                        {
                            Id = 6,
                            Email = "billing@primehealth.com",
                            Name = "Prime Health",
                            PhoneNumber = "+1888999000"
                        },
                        new
                        {
                            Id = 7,
                            Email = "sales@ecoenergy.io",
                            Name = "Eco Energy",
                            PhoneNumber = "+1777111222"
                        },
                        new
                        {
                            Id = 8,
                            Email = "dev@stellarsoft.com",
                            Name = "Stellar Soft",
                            PhoneNumber = "+1666555444"
                        },
                        new
                        {
                            Id = 9,
                            Email = "manager@urbaneats.com",
                            Name = "Urban Eats",
                            PhoneNumber = "+1222999888"
                        },
                        new
                        {
                            Id = 10,
                            Email = "info@bluehorizon.com",
                            Name = "Blue Horizon",
                            PhoneNumber = "+1333444555"
                        },
                        new
                        {
                            Id = 11,
                            Email = "ops@fasttrack.com",
                            Name = "Fast Track",
                            PhoneNumber = "+1999888777"
                        },
                        new
                        {
                            Id = 12,
                            Email = "contact@greenleaf.net",
                            Name = "Green Leaf",
                            PhoneNumber = "+1000111222"
                        },
                        new
                        {
                            Id = 13,
                            Email = "support@nexusit.com",
                            Name = "Nexus IT",
                            PhoneNumber = "+1111222333"
                        },
                        new
                        {
                            Id = 14,
                            Email = "office@skyline.com",
                            Name = "Skyline Const",
                            PhoneNumber = "+1444555666"
                        },
                        new
                        {
                            Id = 15,
                            Email = "wealth@peakfinance.com",
                            Name = "Peak Finance",
                            PhoneNumber = "+1777888999"
                        },
                        new
                        {
                            Id = 16,
                            Email = "ads@novamedia.com",
                            Name = "Nova Media",
                            PhoneNumber = "+1222333444"
                        },
                        new
                        {
                            Id = 17,
                            Email = "land@terrafirma.org",
                            Name = "Terra Firma",
                            PhoneNumber = "+1555444333"
                        },
                        new
                        {
                            Id = 18,
                            Email = "gallery@vividarts.com",
                            Name = "Vivid Arts",
                            PhoneNumber = "+1666777888"
                        },
                        new
                        {
                            Id = 19,
                            Email = "ceo@zenith.com",
                            Name = "Zenith Group",
                            PhoneNumber = "+1888777666"
                        },
                        new
                        {
                            Id = 20,
                            Email = "build@deltaapps.io",
                            Name = "Delta Apps",
                            PhoneNumber = "+1000999888"
                        });
                });

            modelBuilder.Entity("Shared.Common.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContactEmail")
                        .IsUnique();

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Silicon Valley 101",
                            ContactEmail = "info@alphatech.com",
                            Name = "Alpha Tech Group",
                            Phone = "+15550101",
                            TaxId = "76.123.456-1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Industrial Park 45",
                            ContactEmail = "ops@betalog.com",
                            Name = "Beta Logistics SA",
                            Phone = "+15550102",
                            TaxId = "76.123.456-2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Downtown Ave 789",
                            ContactEmail = "hello@gammalab.net",
                            Name = "Gamma Creative Lab",
                            Phone = "+15550103",
                            TaxId = "76.123.456-3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Market Street 12",
                            ContactEmail = "orders@deltafood.com",
                            Name = "Delta Food & Bev",
                            Phone = "+15550104",
                            TaxId = "76.123.456-4"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Green Tower 5",
                            ContactEmail = "admin@epsilon.org",
                            Name = "Epsilon Energy",
                            Phone = "+15550105",
                            TaxId = "76.123.456-5"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Medical Center Plaza",
                            ContactEmail = "care@zetahealth.com",
                            Name = "Zeta Healthcare",
                            Phone = "+15550106",
                            TaxId = "76.123.456-6"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Build Site 99",
                            ContactEmail = "projects@etacon.com",
                            Name = "Eta Construction",
                            Phone = "+15550107",
                            TaxId = "76.123.456-7"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Code Road 404",
                            ContactEmail = "support@theta.io",
                            Name = "Theta Software",
                            Phone = "+15550108",
                            TaxId = "76.123.456-8"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Shopping Mall Wing B",
                            ContactEmail = "sales@iota.com",
                            Name = "Iota Retail",
                            Phone = "+15550109",
                            TaxId = "76.123.456-9"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Wall Street 200",
                            ContactEmail = "finance@kappa.net",
                            Name = "Kappa Finance",
                            Phone = "+15550110",
                            TaxId = "76.123.456-10"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Port Terminal 3",
                            ContactEmail = "fleet@lambda.com",
                            Name = "Lambda Transport",
                            Phone = "+15550111",
                            TaxId = "76.123.456-11"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Creative Hub 10",
                            ContactEmail = "ads@mu.agency",
                            Name = "Mu Marketing",
                            Phone = "+15550112",
                            TaxId = "76.123.456-12"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Signal Way 55",
                            ContactEmail = "noc@nu.com",
                            Name = "Nu Networking",
                            Phone = "+15550113",
                            TaxId = "76.123.456-13"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Global Trade Center",
                            ContactEmail = "export@xi.com",
                            Name = "Xi Exports",
                            Phone = "+15550114",
                            TaxId = "76.123.456-14"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Safe House Blvd",
                            ContactEmail = "protect@omicron.org",
                            Name = "Omicron Security",
                            Phone = "+15550115",
                            TaxId = "76.123.456-15"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Expertise Lane 314",
                            ContactEmail = "advice@piconsult.com",
                            Name = "Pi Consulting",
                            Phone = "+15550116",
                            TaxId = "76.123.456-16"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Property Heights 22",
                            ContactEmail = "rent@rho.com",
                            Name = "Rho Real Estate",
                            Phone = "+15550117",
                            TaxId = "76.123.456-17"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Antenna Hill 1",
                            ContactEmail = "telco@sigma.io",
                            Name = "Sigma Telecom",
                            Phone = "+15550118",
                            TaxId = "76.123.456-18"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Airport View 77",
                            ContactEmail = "travel@tau.com",
                            Name = "Tau Tourism",
                            Phone = "+15550119",
                            TaxId = "76.123.456-19"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Mountain Road 50",
                            ContactEmail = "earth@upsilon.com",
                            Name = "Upsilon Mining",
                            Phone = "+15550120",
                            TaxId = "76.123.456-20"
                        });
                });

            modelBuilder.Entity("Shared.Common.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "emilio@example.com",
                            FirstName = "Emilio",
                            LastName = "Barrera",
                            Password = "Pass123",
                            Phone = "56912345678123456789"
                        },
                        new
                        {
                            Id = 2,
                            Email = "juan.perez@example.com",
                            FirstName = "Juan",
                            LastName = "Perez",
                            Password = "User456",
                            Phone = "56900000000123456780"
                        },
                        new
                        {
                            Id = 3,
                            Email = "m.lopez@example.com",
                            FirstName = "Maria",
                            LastName = "Lopez",
                            Password = "Secret789",
                            Phone = "56900000000123456781"
                        },
                        new
                        {
                            Id = 4,
                            Email = "c.soto@example.com",
                            FirstName = "Carlos",
                            LastName = "Soto",
                            Password = "Admin321",
                            Phone = "56900000000123456782"
                        },
                        new
                        {
                            Id = 5,
                            Email = "a.silva@example.com",
                            FirstName = "Ana",
                            LastName = "Silva",
                            Password = "Power999",
                            Phone = "56900000000123456783"
                        },
                        new
                        {
                            Id = 6,
                            Email = "l.martinez@example.com",
                            FirstName = "Luis",
                            LastName = "Martinez",
                            Password = "Login111",
                            Phone = "56900000000123456784"
                        },
                        new
                        {
                            Id = 7,
                            Email = "e.gomez@example.com",
                            FirstName = "Elena",
                            LastName = "Gomez",
                            Password = "Pass555",
                            Phone = "56900000000123456785"
                        },
                        new
                        {
                            Id = 8,
                            Email = "p.castro@example.com",
                            FirstName = "Pedro",
                            LastName = "Castro",
                            Password = "Word000",
                            Phone = "56900000000123456786"
                        },
                        new
                        {
                            Id = 9,
                            Email = "s.rojas@example.com",
                            FirstName = "Sofia",
                            LastName = "Rojas",
                            Password = "Key1234",
                            Phone = "56900000000123456787"
                        },
                        new
                        {
                            Id = 10,
                            Email = "d.torres@example.com",
                            FirstName = "Diego",
                            LastName = "Torres",
                            Password = "Dev8888",
                            Phone = "56900000000123456788"
                        },
                        new
                        {
                            Id = 11,
                            Email = "l.vargas@example.com",
                            FirstName = "Laura",
                            LastName = "Vargas",
                            Password = "Test222",
                            Phone = "56900000000123456789"
                        },
                        new
                        {
                            Id = 12,
                            Email = "j.herrera@example.com",
                            FirstName = "Jorge",
                            LastName = "Herrera",
                            Password = "Secure9",
                            Phone = "56900000000123456710"
                        },
                        new
                        {
                            Id = 13,
                            Email = "r.mendez@example.com",
                            FirstName = "Rosa",
                            LastName = "Mendez",
                            Password = "Mendez1",
                            Phone = "56900000000123456711"
                        },
                        new
                        {
                            Id = 14,
                            Email = "p.araya@example.com",
                            FirstName = "Pablo",
                            LastName = "Araya",
                            Password = "Araya22",
                            Phone = "56900000000123456712"
                        },
                        new
                        {
                            Id = 15,
                            Email = "c.nunez@example.com",
                            FirstName = "Carmen",
                            LastName = "Nuñez",
                            Password = "Nunez33",
                            Phone = "56900000000123456713"
                        },
                        new
                        {
                            Id = 16,
                            Email = "m.pinto@example.com",
                            FirstName = "Mario",
                            LastName = "Pinto",
                            Password = "Pinto44",
                            Phone = "56900000000123456714"
                        },
                        new
                        {
                            Id = 17,
                            Email = "i.duran@example.com",
                            FirstName = "Isabel",
                            LastName = "Duran",
                            Password = "Duran55",
                            Phone = "56900000000123456715"
                        },
                        new
                        {
                            Id = 18,
                            Email = "a.jara@example.com",
                            FirstName = "Andres",
                            LastName = "Jara",
                            Password = "Jara666",
                            Phone = "56900000000123456716"
                        },
                        new
                        {
                            Id = 19,
                            Email = "p.salas@example.com",
                            FirstName = "Paola",
                            LastName = "Salas",
                            Password = "Salas77",
                            Phone = "56900000000123456717"
                        },
                        new
                        {
                            Id = 20,
                            Email = "r.vega@example.com",
                            FirstName = "Raul",
                            LastName = "Vega",
                            Password = "Vega888",
                            Phone = "56900000000123456718"
                        },
                        new
                        {
                            Id = 21,
                            Email = "g.ruz@example.com",
                            FirstName = "Gloria",
                            LastName = "Ruz",
                            Password = "Ruz9999",
                            Phone = "56900000000123456719"
                        },
                        new
                        {
                            Id = 22,
                            Email = "f.leiva@example.com",
                            FirstName = "Felipe",
                            LastName = "Leiva",
                            Password = "Leiva10",
                            Phone = "56900000000123456720"
                        },
                        new
                        {
                            Id = 23,
                            Email = "m.pena@example.com",
                            FirstName = "Monica",
                            LastName = "Pena",
                            Password = "Pena202",
                            Phone = "56900000000123456721"
                        },
                        new
                        {
                            Id = 24,
                            Email = "h.cano@example.com",
                            FirstName = "Hugo",
                            LastName = "Cano",
                            Password = "Cano303",
                            Phone = "56900000000123456722"
                        },
                        new
                        {
                            Id = 25,
                            Email = "s.bustos@example.com",
                            FirstName = "Silvia",
                            LastName = "Bustos",
                            Password = "Bustos4",
                            Phone = "56900000000123456723"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
